language: clojure
lein: 2.7.1

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

matrix:
  include:
    # terminus unit tests (spec tests)
    - env: PDB_TEST_LANG=ruby PUPPET_VERSION=latest
    - env: PDB_TEST_LANG=ruby PUPPET_VERSION=4.0.0

    # pdb unit tests
    - env: PDB_TEST_LANG=clojure PDB_TEST_SELECTOR=:unit
      jdk: openjdk7
    - env: PDB_TEST_LANG=clojure PDB_TEST_SELECTOR=:unit
      jdk: oraclejdk7
    - env: PDB_TEST_LANG=clojure PDB_TEST_SELECTOR=:unit
      jdk: oraclejdk8

    # pdb + terminus + puppetserver + puppet integration tests
    - env: PDB_TEST_LANG=clojure PDB_TEST_SELECTOR=:integration PUPPET_VERSION=4.6.2 PUPPETSERVER_VERSION=2.7.2
      jdk: oraclejdk8
    - env: PDB_TEST_LANG=clojure PDB_TEST_SELECTOR=:integration PUPPET_VERSION=latest PUPPETSERVER_VERSION=master
      jdk: oraclejdk8

before_install: ext/travisci/install_puppetserver.sh
script: ext/travisci/test.sh

notifications:
  email: false

# Host addons handle buffer overflow in jdk 7 with travis' long
# hostnames:
#   https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
#   http://mail.openjdk.java.net/pipermail/net-dev/2012-July/004603.html
#   http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7089443
#   http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7112670

addons:
  hosts:
    - pdbtest
  hostname: pdbtest
  postgresql: "9.4"

services: postgresql
